<?php

/**
 * @file
 * Contains reseau_mod_up.module.
 */


// /**
//  * Implements hook_entity_type_alter().
//  *
//  * @param array $entity_types
//  */
// function reseau_mod_up_entity_type_alter(array &$entity_types)
// {
//   // Add validation constraint to the node entity
//   if (isset($entity_types['node'])) {
//     $entity_types['node']->addConstraint('AtLeastOneFormationIdentifier');

//     // dsm($entity_types['node']);
//   }
// }


function reseau_mod_up_page_attachments_alter(array &$attachments)
{

//   /*ajoute css admin*/
//   $admin_theme = \Drupal::config('system.theme')->get('admin');
//   $admin_theme_name = \Drupal::service('theme_handler')->getName($admin_theme);
//   if ($admin_theme_name == 'Seven') {
//     $attachments['#attached']['library'][] = 'reseau_mod_up/extra.admin';
//   }

$attachments['#attached']['library'][] = 'reseau_mod_up/extra.adminreseauup';

}

function reseau_mod_up_preprocess_html(&$variables)
{

    foreach ($variables['user']->getRoles() as $role) {
        $variables['attributes']['class'][] = 'role-' . $role;
      }
}