<?php

/**
 * @file
 * Contains reseau_mod_up_blocageedition.module.
 */

function reseau_mod_up_blocageedition_page_attachments_alter(array &$attachments)
{
    /*ajoute css admin*/
    $admin_theme = \Drupal::config('system.theme')->get('admin');
    $admin_theme_name = \Drupal::service('theme_handler')->getName($admin_theme);
    if ($admin_theme_name == 'Seven') {
        $attachments['#attached']['library'][] = 'reseau_mod_up_blocageedition/extra.contenusbloques';
        // /* charge library si role est webmaster structures */
        $current_user = \Drupal::entityTypeManager()->getStorage('user')->load(\Drupal::currentUser()->id());
        if (($current_user->hasRole('administrator')) || ($current_user->hasRole('webmaster_reseau'))  || ($current_user->id() == '1')) {
            return;
        } else {
            $attachments['#attached']['library'][] = 'reseau_mod_up_blocageedition/extra.webmasterstructures';
        }
    }
}
